// flow-typed signature: 6008ae9c985cebd5590b58af315a1d84
// flow-typed version: <<STUB>>/@openlattice/access-request_v0.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@openlattice/access-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@openlattice/access-request' {
  declare module.exports: any;
}
