// flow-typed signature: 39e0cb50356c9ae8345eae8c5509208b
// flow-typed version: <<STUB>>/react-select_v2.1.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}
