const DBMS_TYPES = {
  'IMC/Pervasive SQL': {
    connection: 'pervasive',
    connectionSuffix: '?transport=tcp',
    driver: 'com.pervasive.jdbc.v2.Driver',
    port: 1583,
    sqlStatement: 'SELECT * FROM MasterNameVitals',
  },
  'IBM DB2': {
    connection: 'db2',
    connectionSuffix: '',
    driver: 'COM.ibm.db2.jdbc.app.DB2Driver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'JDBC-ODBC Bridge': {
    connection: 'odbc',
    connectionSuffix: '',
    driver: 'sun.jdbc.odbc.JdbcOdbcDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Microsoft SQL Server': {
    connection: 'weblogic',
    connectionSuffix: '',
    driver: 'weblogic.jdbc.mssqlserver4.Driver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'PointBase Embedded Server': {
    connection: 'pointbase',
    connectionSuffix: '',
    driver: 'com.pointbase.jdbc.jdbcUniversalDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  Cloudscape: {
    connection: 'cloudscape',
    connectionSuffix: '',
    driver: 'COM.cloudscape.core.JDBCDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Cloudscape RMI': {
    connection: 'rmi',
    connectionSuffix: '',
    driver: 'RmiJdbc.RJDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Firebird (JCA/JDBC Driver)': {
    connection: 'firebirdsql',
    connectionSuffix: '',
    driver: 'org.firebirdsql.jdbc.FBDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'IDS Server': {
    connection: 'ids',
    connectionSuffix: '',
    driver: 'ids.sql.IDSDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'QED/Informix Dynamic Server': {
    connection: 'informix-sqli',
    connectionSuffix: ':informixserver=<serverNameHere>;DELIMIDENT=Y',
    driver: 'com.informix.jdbc.IfxDriver',
    port: 9088,
    sqlStatement: 'INFO TABLES',
  },
  'InstantDB (v3.13 and earlier)': {
    connection: 'idb',
    connectionSuffix: '',
    driver: 'jdbc.idbDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'InstantDB (v3.14 and later)': {
    connection: 'idb',
    connectionSuffix: '',
    driver: 'org.enhydra.instantdb.jdbc.idbDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Interbase (InterClient Driver)': {
    connection: 'interbase',
    connectionSuffix: '',
    driver: 'interbase.interclient.Driver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Hypersonic SQL (v1.2 and earlier)': {
    connection: 'HypersonicSQL',
    connectionSuffix: '',
    driver: 'hSql.hDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Hypersonic SQL (v1.3 and later)': {
    connection: 'HypersonicSQL',
    connectionSuffix: '',
    driver: 'org.hsql.jdbcDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Microsoft SQL Server (JTurbo Driver)': {
    connection: 'JTurbo',
    connectionSuffix: '',
    driver: 'com.ashna.jturbo.driver.Driver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Microsoft SQL Server (Sprinta Driver)': {
    connection: 'inetdae',
    connectionSuffix: '',
    driver: 'com.inet.tds.TdsDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Microsoft SQL Server 2000 (Microsoft Driver)': {
    connection: 'microsoft',
    connectionSuffix: '',
    driver: 'com.microsoft.jdbc.sqlserver.SQLServerDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'MySQL (MM.MySQL Driver)': {
    connection: 'mysql',
    connectionSuffix: '',
    driver: 'org.gjt.mm.mysql.Driver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  Oracle: {
    connection: 'oracle',
    connectionSuffix: '',
    driver: 'oracle.jdbc.driver.OracleDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'PostgreSQL (v6.5 and earlier)': {
    connection: 'postgresql',
    connectionSuffix: '',
    driver: 'postgresql.Driver',
    port: 5432,
    sqlStatement: 'SELECT * FROM pg_catalog.pg_tables',
  },
  'PostgreSQL (v7.0 and later)': {
    connection: 'postgresql',
    connectionSuffix: '',
    driver: 'org.postgresql.Driver',
    port: 5432,
    sqlStatement: 'SELECT * FROM pg_catalog.pg_tables',
  },
  SnappyData: {
    connection: 'snappydata',
    connectionSuffix: '',
    driver: 'com.pivotal.gemfirexd.jdbc.ClientDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  SqlBase: {
    connection: 'sqlbase',
    connectionSuffix: '',
    driver: 'jdbc.gupta.sqlbase.SqlbaseDriver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Sybase (jConnect 4.2 and earlier)': {
    connection: 'sybase',
    connectionSuffix: '',
    driver: 'com.sybase.jdbc.SybDriver',
    port: 5000,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Sybase (jConnect 5.2)': {
    connection: 'sybase',
    connectionSuffix: '',
    driver: 'com.sybase.jdbc2.jdbc.SybDriver',
    port: 5000,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Sybase ASE': {
    connection: 'sybase:Tds',
    connectionSuffix: '',
    driver: 'net.sourceforge.jtds.jdbc.Driver',
    port: 5000,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  'Sybase SqlAnywhere': {
    connection: 'sybase:Tds',
    connectionSuffix: '',
    driver: 'com.sybase.jdbc3.jdbc.SybDriver',
    port: 5000,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  Transbase: {
    connection: 'transbase',
    connectionSuffix: '',
    driver: 'transbase.jdbc.Driver',
    port: 0,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  },
  Vertica: {
    connection: 'vertica',
    connectionSuffix: '',
    driver: 'com.vertica.jdbc.Driver',
    port: 5433,
    sqlStatement: 'SELECT * FROM <metaTableGoesHere>',
  }
};

export default DBMS_TYPES;
